### ISSUE TITLE
Lists show no number or bullet

### ISSUE THREAD

**Issue by 52buickman** [zerostaticthemes/hugo-hero-theme#48]
I'm using Firefox v99.0 64bit.

The text on the list item is indented, but shows no number for ordered lists nor bullet icon on the unordered list.  You can see the effect on the example demo.

**Comment by 52buickman** [comment]
Tried it with Brave Browser Version 1.38.111 Chromium: 101.0.4951.54 (Official Build) (64-bit) as well.  No list items were denoted with a Chromium based browser.

**Comment by colinjnash** [comment]
Same issue here. I'm going to look at the CSS and try and find a workaround.

**Comment by colinjnash** [comment]
Under **assets > scss > components > reset.scss** 

```css
ul,
ol {
  margin: 0;
  padding: 0;
  list-style: disc !important;
}

```
