### ISSUE TITLE
Renaming of "services" and "work" sections

### ISSUE THREAD

**Issue by yonz2** [zerostaticthemes/hugo-hero-theme#66]
Hi,

I am trying to change the names of the  "services" (New: Offerings) and "work" (New: Methods) sections. [I followed this documentation](https://www.zerostatic.io/docs/hugo-advance/guides/renaming-a-section/) , but that only renames the folders and menus. In the `content/en/_index.md` file I have the following in the Frontmatter:
```
services:
  enabled: true
  show_view_all: true
  sort_by: "weight" # "date" "weight"
  limit: 2
 ...
work:
  enabled: true
  show_view_all: false
  limit: 4
```
What do I have to do to make this work with the renamed sections?
And this also creates additional Menu Items "work" and "services". How can I rename them as well?

I like this feature of the Theme, to display the "services" and "work" dynamically. So I would like to use it, but under another name...

Any help will be much appreciated!

Yonz
